"""Canonical contract vocabulary for localized certification artifacts."""

from __future__ import annotations

import re


ALIASES: dict[str, tuple[str, ...]] = {
    "## Scope": ("## 范围",),
    "## Capability Inventory": ("## 能力清单",),
    "## Permission Modes": ("## 权限模式",),
    "## Context Recovery": ("## Context 恢复",),
    "## Autonomous Boundary": ("## 自主边界",),
    "## Worktree Ownership": ("## Worktree 所有权",),
    "## Hook Decision": ("## Hook 决策",),
    "## Scheduled Execution": ("## 定时执行",),
    "## Review Automation": ("## 审查自动化",),
    "## Allowed Fixture": ("## 允许的 Fixture",),
    "## Denied Fixture": ("## 拒绝的 Fixture",),
    "## Version Evidence": ("## 版本证据",),
    "## Rollback": ("## 回滚",),
    "## Goal and Scope": ("## 目标与范围",),
    "## Tasks and Dependencies": ("## 任务与依赖",),
    "## Result States": ("## 结果状态",),
    "## Budgets": ("## 预算",),
    "## Merge Rules": ("## 合并规则",),
    "## Independent Review": ("## 独立审查",),
    "## Durable State": ("## 持久化状态",),
    "## Revalidation": ("## 重新验证",),
    "## Side Effect Reconciliation": ("## 副作用对账",),
    "## Context Budget": ("## Context 预算",),
    "## Catalog Boundary": ("## 目录边界",),
    "## Tool Contracts": ("## Tool 契约",),
    "## Error Matrix": ("## 错误Matrix", "## 错误 Matrix"),
    "## Progressive Discovery": ("## 渐进式发现",),
    "## Authorization": ("## 授权",),
    "## Selection Fixtures": ("## 选择 Fixture",),
    "## Instruction Hierarchy": ("## 指令层级",),
    "## Path Rule Fixtures": ("## 路径规则 Fixtures",),
    "## Skill and Command": ("## Skill 与 Command",),
    "## Skill Package": ("## Skill 包",),
    "## Subagent Contract": ("## Subagent 契约",),
    "## Plugin Distribution": ("## Plugin 分发",),
    "## Remediation": ("## 修复",),
    "## Extraction Contract": ("## 抽取契约",),
    "## Batch Manifest": ("## 批处理清单",),
    "## Validation Layers": ("## 验证层",),
    "## Reviewer Findings": ("## 审阅者发现",),
    "## Adjudication": ("## 裁决",),
    "## Metrics": ("## 指标",),
    "## Scope and Coverage": ("## 范围与覆盖情况",),
    "## Provenance Envelope": ("## 溯源封装",),
    "## Partial Result": ("## 部分结果",),
    "## Conflict": ("## 冲突",),
    "## Escalation": ("## 升级",),
    "## Human Review": ("## 人工审查", "## 人工审核"),
    "## Outcome": ("## 结果",),
    "## Requirements": ("## 需求",),
    "## Data and Authority": ("## 数据与权限",),
    "## Measures": ("## 衡量指标",),
    "## Assumptions": ("## 假设",),
    "## Non-Goals": ("## 非目标",),
    "## Decision": ("## 决策",),
    "## Candidate Scores": ("## 候选方案评分",),
    "## Hard Gates": ("## 硬性门禁",),
    "## Failure Paths": ("## 故障路径",),
    "## Rejected Alternatives": ("## 被拒绝的替代方案",),
    "## Reversal Condition": ("## 反转条件", "## 逆转条件"),
    "## Risk Register": ("## 风险登记册",),
    "## Data Map": ("## 数据地图",),
    "## Control Matrix": ("## 控制Matrix", "## 控制 Matrix"),
    "## Fallback": ("## Fallback",),
    "## Reassessment": ("## 重新评估",),
    "## Executive Decision": ("## 管理层决策",),
    "## Contract Index": ("## 契约索引",),
    "## Operational Readiness": ("## 运营就绪情况",),
    "## Ownership Map": ("## 所有权映射",),
    "owner": ("所有者", "负责人"),
    "pinned": ("固定",),
    "version": ("版本",),
    "rollback": ("回滚",),
    "deny rule": ("deny 规则",),
    "turn bound": ("轮次上限",),
    "budget": ("预算",),
    "allowed tools": ("允许的只读 Tool", "允许的 Tool"),
    "conflict": ("冲突",),
    "isolated": ("隔离",),
    "revalidate": ("重新验证", "再次验证"),
    "idempotency": ("幂等",),
    "unknown outcome": ("未知结果", "结果未知"),
    "blocked": ("阻塞", "受阻"),
    "validation": ("验证",),
    "authorization": ("授权",),
    "non-retryable": ("不可重试",),
    "partial": ("部分",),
    "execution": ("执行",),
    "use when": ("何时使用", "适用场景", "时使用"),
    "do not use": ("不要使用", "不适用", "不得用于"),
    "fresh checkout": ("全新 checkout", "干净 checkout"),
    "read-only": ("只读",),
    "structured": ("结构化",),
    "pre-write hook": ("写入前 Hook", "写入前 hook", "操作前 Hook"),
    "deterministic": ("确定性",),
    "exit 0": ("退出码为 0", "退出码 0"),
    "exit 2": ("退出码为 2", "退出码 2"),
    "migration": ("迁移",),
    "when": ("适用于", "当",),
    "syntax": ("语法",),
    "semantic": ("语义",),
    "provenance": ("溯源", "来源",),
    "shuffled": ("乱序", "打乱",),
    "24-hour": ("24 小时",),
    "no guaranteed latency": ("不保证延迟", "无延迟保证"),
    "independent": ("独立",),
    "adjudication": ("裁决",),
    "18 of 24": ("24 个来源中有 18 个", "18/24", "已审查其中 18 个"),
    "omitted": ("省略", "未包含", "遗漏"),
    "source version": ("来源版本", "源版本"),
    "content type": ("内容类型",),
    "location": ("位置",),
    "safe next action": ("安全的下一步操作",),
    "random sample": ("随机抽样", "随机样本"),
    "baseline": ("基线",),
    "target": ("目标",),
    "constraint": ("约束",),
    "estimate": ("估计", "估算"),
    "autonomous sending": ("自主发送", "自动发送"),
    "workflow": ("工作流",),
    "latency": ("延迟",),
    "safety": ("安全",),
    "reversal": ("反转", "逆转"),
    "preventive": ("预防性",),
    "detective": ("检测性", "侦测性"),
    "corrective": ("纠正性",),
    "governance": ("治理",),
    "qualified": ("合格", "具备资质"),
    "manual urgent-triage queue": ("人工紧急分诊队列",),
    "queue slo": ("队列 SLO",),
    "material change": ("重大变更", "实质性变更"),
    "alert": ("告警", "警报"),
    "rejected": ("拒绝", "被拒绝"),
    "tabletop": ("桌面演练", "桌面推演"),
}


def canonical_contract_text(text: str) -> str:
    present = text
    lowered = text.lower()
    for canonical, aliases in ALIASES.items():
        if canonical.lower() in lowered:
            continue
        if any(alias.lower() in lowered for alias in aliases):
            present += "\n" + canonical
    return present


def without_contract_terms(text: str, *canonical_terms: str) -> str:
    """Remove canonical terms and every localized alias for negative tests."""
    output = text
    for canonical in canonical_terms:
        for term in (canonical, *ALIASES.get(canonical, ())):
            output = re.sub(re.escape(term), "", output, flags=re.IGNORECASE)
    return output
